ARG BASE_IMAGE
FROM ${BASE_IMAGE}

COPY tests/entrypoint.sh /entrypoint.sh

WORKDIR /rpm-shim
COPY . .

ARG INSTALL_DEPS_CMD
RUN sh -c "${INSTALL_DEPS_CMD}"

RUN python3 -m pip install tox build || python3 -m pip install --break-system-packages tox build

WORKDIR /
ENTRYPOINT ["/entrypoint.sh"]
